### ISSUE TITLE
Postman Import not working

### ISSUE THREAD

**Issue by Ombrelin** [jenius-apps/nightingale-core#5]
While trying to import a postman collection I got the following error : 
> Object reference not set to an instance of an object

[shiori.postman_collection.json.zip](https://github.com/jenius-apps/nightingale-core/files/5565106/shiori.postman_collection.json.zip)

**Comment by dpaulino** [comment]
Thanks for the report. What version of nightingale are you using right now?

**Comment by Ombrelin** [comment]
Hello, thanks for your response, my version of Nightingale is 4.3.20

**Comment by dpaulino** [comment]
Can you try heading to the store and getting the latest version which is 4.3.4 and then trying again? I think the issue may still be there, but I just want to check

**Comment by Ombrelin** [comment]
I just upgraded to 4.3.4 and sadly, the problem is still the same

**Comment by dpaulino** [comment]
Ok thanks I'll investigate!

**Comment by dpaulino** [comment]
@Ombrelin thank you for the report! The next release of nightingale will include this fix!

**Comment by dpaulino** [comment]
Here's how it looks after importing btw
![image](https://user-images.githubusercontent.com/7649589/99868045-d9308080-2b73-11eb-99b6-75a0b5139328.png)
